### ISSUE TITLE
Please clarify the license for visualizer.json2html

### ISSUE THREAD

**Issue by JamesHough** [moappi/visualizer.json2html#1]
Please add a license file to the source code repository or to the JS file so that we know how to comply with license requirements.

The website http://visualizer.json2html.com/ doesn't have a mention of the license for Visualizer (although, the MIT license is mentioned on http://www.json2html.com/ - But this wouldn't automatically apply to work dependent on the library).

The lib/index.js file also doesn't contain copyright or license information.

Although I could create transformers to do something similar, trying to avoid exactly what you have done, the script I made probably wouldn't differ enough from this project in order to be considered separate works and I could be putting my corporate client at risk of copyright infringement (if at any time in future you applied a license that I am not complying with).

**Comment by aalimovs** [comment]
Can be closed now, license added via https://github.com/moappi/visualizer.json2html/pull/3

**Comment by moappi** [comment]
License Added
